/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useRef, useEffect, useCallback } from 'react';
import { GoogleGenAI, Type, Modality } from "@google/genai";
import { Upload, Leaf, RefreshCw, CheckCircle2, AlertCircle, Info, Camera, FileText, LogOut, History, User as UserIcon, Mail, Lock, UserPlus, ArrowRight, Star, Filter, Bell, MessageCircle, Mic, MicOff, Maximize2, Minimize2, Check, Loader2, Send, X, LayoutGrid, Activity, Trash2 } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import Markdown from 'react-markdown';
import { jsPDF } from 'jspdf';
import { auth, db, googleProvider, signInWithPopup, signOut, onAuthStateChanged, collection, addDoc, query, where, orderBy, onSnapshot, serverTimestamp, Timestamp, User, createUserWithEmailAndPassword, signInWithEmailAndPassword, updateProfile, doc, updateDoc, deleteDoc } from './firebase';

// Initialize Gemini API
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

interface AnalysisResult {
  id?: string;
  disease: string;
  severity: 'Low' | 'Medium' | 'High';
  confidence: string;
  solution: string;
  details: string;
  imageUrl?: string;
  isFavorite?: boolean;
  highlights?: { box_2d: number[]; label: string }[];
  progressStatus?: 'initial' | 'improving' | 'worsening' | 'recovered';
  createdAt?: Timestamp;
}

interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

interface AnalysisStep {
  id: string;
  label: string;
  status: 'pending' | 'loading' | 'completed';
}

const translations = {
  en: {
    appName: "CropGuard AI Pro",
    title: "CropGuard AI",
    welcome: "Welcome back, farmer!",
    join: "Join our farming community",
    chooseAuth: "Choose a sign in method",
    scanHistory: "Scan History",
    backToScanner: "Back to Scanner",
    captureUpload: "Capture or Upload Leaf",
    upload: "Upload Leaf Image",
    camera: "Camera",
    analyze: "Analyze Leaf Health",
    result: "Result",
    diagnosis: "Diagnosis",
    disease: "Disease",
    confidence: "Confidence",
    confidenceLabel: "Confidence Level",
    treatment: "Recommended Treatment",
    analysis: "Detailed Analysis",
    details: "Detailed Analysis",
    report: "Download Report",
    newScan: "New Scan",
    askExpert: "Ask Expert",
    chatPlaceholder: "Ask for point-wise expert advice...",
    healthy: "Healthy",
    diseased: "Diseased",
    severity: "Severity",
    processing: "Identifying disease patterns...",
    favorites: "Favorites",
    allScans: "All Scans",
    low: "Low",
    medium: "Medium",
    high: "High",
    voiceTemplate: (d: string, c: string, s: string, t: string) => `Analysis complete. We identified ${d} with ${c} confidence. The severity is ${s}. Recommended treatment: ${t}.`,
    noFavorites: "No favorite scans found.",
    noScans: "No scans found. Start scanning leaves to build your history.",
    pdfTitle: "Crop Health Pro Report",
    pdfFilename: "Crop_Report",
    pdfGeneratedOn: "Generated on",
    pdfDiagnosis: "Diagnosis",
    pdfTreatment: "Recommended Treatment",
    pdfAnalysisDetails: "Analysis Details",
    pdfFooter: "This report is generated by CropGuard AI Pro. Consult an expert for critical decisions.",
    notifTitle: "Disease Detected!",
    notifBody: (d: string) => `We found ${d} on your crop. Check the solution.`,
    tipLabel: "Tip",
    tip: "For best results, ensure the leaf is well-lit and centered. Avoid blurry images or backgrounds with too many other plants.",
    match: "Match",
    signIn: "Sign In",
    createAccount: "Create Account",
    or: "Or",
    continueWithGoogle: "Continue with Google",
    noAccount: "Don't have an account?",
    register: "Register",
    hasAccount: "Already have an account?",
    login: "Login",
    terms: "By continuing, you agree to our terms of service and privacy policy.",
    poweredBy: "Secure authentication powered by Firebase.",
    email: "Email Address",
    password: "Password",
    notifEnabled: "Notifications Enabled",
    enableNotif: "Enable Notifications",
    history: "History",
    farmerAccount: "Farmer Account",
    signOut: "Sign Out",
    deleteScan: "Delete Scan",
    fullName: "Full Name",
    noAnalysis: "No Analysis Yet",
    noAnalysisDesc: "Upload a leaf photo to see AI-powered health insights here.",
    analysisError: "Analysis Error",
    tryAgain: "Try Again",
    footerText: "This AI tool is for informational purposes. Always consult a local agricultural expert for critical decisions.",
    errorGeneric: "An error occurred. Please try again.",
    errorGoogle: "Failed to sign in with Google.",
    errorEmailInUse: "This email is already registered.",
    errorInvalidCreds: "Invalid email or password.",
    errorWeakPassword: "Password should be at least 6 characters.",
    errorAuth: "Authentication failed. Please check your details.",
    errorChatbot: "I'm having trouble connecting to my knowledge base. Please try again.",
    errorChatbotFallback: "I'm sorry, I couldn't process that.",
    errorAnalysis: "Failed to analyze the image. Please try again with a clearer photo.",
    chatContext: (d: string, s: string, t: string) => `The current scan shows ${d} with ${s} severity. Treatment: ${t}.`,
    chatNoContext: "No scan has been performed yet.",
    steps: [
      "Image processed",
      "Spots detected",
      "Pattern matched",
      "Disease identified",
      "Treatment suggested"
    ],
    voiceImproving: "Your plant condition is improving!",
    voiceWorsening: "Warning: The disease is spreading. Please take action immediately.",
    voiceRecovered: "Your plant is fully recovered!",
    voiceInitial: "Initial diagnosis complete.",
    timeline: "Timeline",
    progress: "Progress",
    improving: "Improving",
    worsening: "Worsening",
    recovered: "Recovered",
    initial: "Initial",
    voiceMode: "Voice Mode",
    voiceModeDesc: "App will speak progress updates"
  },
  ta: {
    appName: "கிராப்கார்டு AI",
    title: "கிராப்கார்டு AI",
    welcome: "மீண்டும் வருக, விவசாயியே!",
    join: "எங்கள் விவசாய சமூகத்தில் இணையுங்கள்",
    chooseAuth: "உள்நுழைவு முறையைத் தேர்ந்தெடுக்கவும்",
    scanHistory: "ஸ்கேன் வரலாறு",
    backToScanner: "ஸ்கேனருக்குத் திரும்பு",
    captureUpload: "இலையைப் படம் பிடிக்கவும் அல்லது பதிவேற்றவும்",
    upload: "இலை படத்தை பதிவேற்றவும்",
    camera: "கேமரா",
    analyze: "இலை ஆரோக்கியத்தைப் பகுப்பாய்வு செய்",
    result: "முடிவு",
    diagnosis: "நோய் கண்டறிதல்",
    disease: "நோய்",
    confidence: "நம்பிக்கை அளவு",
    confidenceLabel: "நம்பிக்கை நிலை",
    treatment: "பரிந்துரைக்கப்பட்ட சிகிச்சை",
    analysis: "விரிவான பகுப்பாய்வு",
    details: "விரிவான பகுப்பாய்வு",
    report: "அறிக்கை பதிவிறக்கம்",
    newScan: "புதிய ஸ்கேன்",
    askExpert: "நிபுணரிடம் கேளுங்கள்",
    chatPlaceholder: "புள்ளி வாரியான நிபுணர் ஆலோசனையைக் கேளுங்கள்...",
    healthy: "ஆரோக்கியமானது",
    diseased: "நோய் பாதித்தது",
    severity: "தீவிரம்",
    processing: "நோய் வடிவங்களை அடையாளம் காணுதல்...",
    favorites: "விருப்பமானவை",
    allScans: "அனைத்து ஸ்கேன்கள்",
    low: "குறைவு",
    medium: "நடுத்தரம்",
    high: "அதிகம்",
    voiceTemplate: (d: string, c: string, s: string, t: string) => `பகுப்பாய்வு முடிந்தது. உங்கள் பயிரில் ${d} கண்டறியப்பட்டுள்ளது. இதன் துல்லியம் ${c}. நோயின் தீவிரம் ${s}. பரிந்துரைக்கப்பட்ட தீர்வு: ${t}.`,
    noFavorites: "விருப்பமான ஸ்கேன்கள் எதுவும் இல்லை.",
    noScans: "ஸ்கேன்கள் எதுவும் இல்லை. உங்கள் வரலாற்றை உருவாக்க இலைகளை ஸ்கேன் செய்யத் தொடங்குங்கள்.",
    pdfTitle: "பயிர் ஆரோக்கிய அறிக்கை",
    pdfFilename: "பயிர்_அறிக்கை",
    pdfGeneratedOn: "உருவாக்கப்பட்டது",
    pdfDiagnosis: "நோய் கண்டறிதல்",
    pdfTreatment: "பரிந்துரைக்கப்பட்ட சிகிச்சை",
    pdfAnalysisDetails: "பகுப்பாய்வு விவரங்கள்",
    pdfFooter: "இந்த அறிக்கை கிராப்கார்டு AI மூலம் உருவாக்கப்பட்டது. முக்கியமான முடிவுகளுக்கு நிபுணரை அணுகவும்.",
    notifTitle: "நோய் கண்டறியப்பட்டது!",
    notifBody: (d: string) => `உங்கள் பயிரில் ${d} கண்டறியப்பட்டுள்ளது. தீர்வைச் சரிபார்க்கவும்.`,
    tipLabel: "குறிப்பு",
    tip: "சிறந்த முடிவுகளுக்கு, இலை நன்கு வெளிச்சமாகவும் மையமாகவும் இருப்பதை உறுதி செய்யவும். மங்கலான படங்கள் அல்லது அதிக செடிகள் உள்ள பின்னணியைத் தவிர்க்கவும்.",
    match: "பொருத்தம்",
    signIn: "உள்நுழைக",
    createAccount: "கணக்கை உருவாக்கு",
    or: "அல்லது",
    continueWithGoogle: "கூகுள் மூலம் தொடரவும்",
    noAccount: "கணக்கு இல்லையா?",
    register: "பதிவு செய்க",
    hasAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    login: "உள்நுழைக",
    terms: "தொடர்வதன் மூலம், எங்கள் சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கிறீர்கள்.",
    poweredBy: "ஃபயர்பேஸ் மூலம் பாதுகாப்பான அங்கீகாரம்.",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    notifEnabled: "அறிவிப்புகள் இயக்கப்பட்டுள்ளன",
    enableNotif: "அறிவிப்புகளை இயக்கு",
    history: "வரலாறு",
    farmerAccount: "விவசாயி கணக்கு",
    signOut: "வெளியேறு",
    deleteScan: "ஸ்கேனை நீக்கு",
    fullName: "முழு பெயர்",
    noAnalysis: "இன்னும் பகுப்பாய்வு இல்லை",
    noAnalysisDesc: "AI மூலம் இயங்கும் சுகாதார நுண்ணறிவுகளை இங்கே காண இலை புகைப்படத்தைப் பதிவேற்றவும்.",
    analysisError: "பகுப்பாய்வு பிழை",
    tryAgain: "மீண்டும் முயற்சிக்கவும்",
    footerText: "இந்த AI கருவி தகவல் நோக்கங்களுக்காக மட்டுமே. முக்கியமான முடிவுகளுக்கு எப்போதும் உள்ளூர் விவசாய நிபுணரை அணுகவும்.",
    errorGeneric: "ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    errorGoogle: "கூகுள் மூலம் உள்நுழைவதில் தோல்வி.",
    errorEmailInUse: "இந்த மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.",
    errorInvalidCreds: "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.",
    errorWeakPassword: "கடவுச்சொல் குறைந்தது 6 எழுத்துக்களைக் கொண்டிருக்க வேண்டும்.",
    errorAuth: "அங்கீகாரம் தோல்வியடைந்தது. உங்கள் விவரங்களைச் சரிபார்க்கவும்.",
    errorChatbot: "எனது அறிவுத் தளத்துடன் இணைப்பதில் சிக்கல் உள்ளது. மீண்டும் முயற்சிக்கவும்.",
    errorChatbotFallback: "மன்னிக்கவும், என்னால் அதைச் செயல்படுத்த முடியவில்லை.",
    errorAnalysis: "படத்தைப் பகுப்பாய்வு செய்வதில் தோல்வி. தெளிவான புகைப்படத்துடன் மீண்டும் முயற்சிக்கவும்.",
    chatContext: (d: string, s: string, t: string) => `தற்போதைய ஸ்கேன் ${d} ஐ ${s} தீவிரத்துடன் காட்டுகிறது. சிகிச்சை: ${t}.`,
    chatNoContext: "இன்னும் ஸ்கேன் எதுவும் செய்யப்படவில்லை.",
    steps: [
      "படம் செயலாக்கப்பட்டது",
      "புள்ளிகள் கண்டறியப்பட்டன",
      "வடிவம் பொருந்தியது",
      "நோய் அடையாளம் காணப்பட்டது",
      "சிகிச்சை பரிந்துரைக்கப்பட்டது"
    ],
    voiceImproving: "உங்கள் பயிரின் நிலை மேம்பட்டு வருகிறது!",
    voiceWorsening: "எச்சரிக்கை: நோய் பரவி வருகிறது. உடனடியாக நடவடிக்கை எடுக்கவும்.",
    voiceRecovered: "உங்கள் பயிர் முழுமையாக குணமடைந்தது!",
    voiceInitial: "ஆரம்ப கட்ட நோய் கண்டறிதல் முடிந்தது.",
    timeline: "காலவரிசை",
    progress: "முன்னேற்றம்",
    improving: "மேம்படுகிறது",
    worsening: "மோசமடைகிறது",
    recovered: "குணமடைந்தது",
    initial: "ஆரம்பம்",
    voiceMode: "குரல் முறை",
    voiceModeDesc: "பயன்பாடு முன்னேற்ற அறிவிப்புகளைப் பேசும்"
  },
  hi: {
    appName: "क्रॉपगार्ड AI प्रो",
    title: "क्रॉपगार्ड AI",
    welcome: "वापस स्वागत है, किसान भाई!",
    join: "हमारे किसान समुदाय में शामिल हों",
    chooseAuth: "साइन इन विधि चुनें",
    scanHistory: "स्कैन इतिहास",
    backToScanner: "स्कैनर पर वापस जाएं",
    captureUpload: "पत्ती की फोटो लें या अपलोड करें",
    upload: "अपलोड करें",
    camera: "कैमरा",
    analyze: "पत्ती के स्वास्थ्य का विश्लेषण करें",
    result: "परिणाम",
    diagnosis: "रोग निदान",
    disease: "रोग",
    treatment: "अनुशंसित उपचार",
    confidence: "सटीकता",
    confidenceLabel: "सटीकता स्तर",
    analysis: "विस्तृत विश्लेषण",
    details: "विस्तृत विश्लेषण",
    report: "रिपोर्ट पीडीएफ",
    newScan: "नया स्कैन",
    askExpert: "विशेषज्ञ से पूछें",
    chatPlaceholder: "बिंदुवार विशेषज्ञ सलाह मांगें...",
    healthy: "स्वस्थ",
    diseased: "रोगग्रस्त",
    severity: "गंभीरता",
    processing: "रोग के पैटर्न की पहचान की जा रही है...",
    favorites: "पसंदीदा",
    allScans: "सभी स्कैन",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    voiceTemplate: (d: string, c: string, s: string, t: string) => `विश्लेषण पूरा हो गया है। आपकी फसल में ${d} की पहचान की गई है। इसकी सटीकता ${c} है। रोग की गंभीरता ${s} है। सुझाई गई उपचार विधि है: ${t}।`,
    noFavorites: "कोई पसंदीदा स्कैन नहीं मिला।",
    noScans: "कोई स्कैन नहीं मिला। अपना इतिहास बनाने के लिए पत्तियों को स्कैन करना शुरू करें।",
    pdfTitle: "फसल स्वास्थ्य प्रो रिपोर्ट",
    pdfFilename: "फसल_रिपोर्ट",
    pdfGeneratedOn: "जनरेट किया गया",
    pdfDiagnosis: "रोग निदान",
    pdfTreatment: "अनुशंसित उपचार",
    pdfAnalysisDetails: "विश्लेषण विवरण",
    pdfFooter: "यह रिपोर्ट क्रॉपगार्ड AI प्रो द्वारा जनरेट की गई है। महत्वपूर्ण निर्णयों के लिए विशेषज्ञ से सलाह लें।",
    notifTitle: "रोग का पता चला!",
    notifBody: (d: string) => `आपकी फसल पर ${d} पाया गया है। समाधान देखें।`,
    tipLabel: "सुझाव",
    tip: "सर्वोत्तम परिणामों के लिए, सुनिश्चित करें कि पत्ती अच्छी तरह से प्रकाशित और केंद्रित है। धुंधली छवियों या बहुत अधिक पौधों वाले बैकग्राउंड से बचें।",
    match: "मैच",
    signIn: "साइन इन करें",
    createAccount: "खाता बनाएं",
    or: "या",
    continueWithGoogle: "गूगल के साथ जारी रखें",
    noAccount: "खाता नहीं है?",
    register: "पंजीकरण करें",
    hasAccount: "पहले से ही एक खाता है?",
    login: "लॉगिन करें",
    terms: "जारी रखकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं।",
    poweredBy: "फायरबेस द्वारा सुरक्षित प्रमाणीकरण।",
    email: "ईमेल पता",
    password: "पासवर्ड",
    notifEnabled: "सूचनाएं सक्षम हैं",
    enableNotif: "सूचनाएं सक्षम करें",
    history: "इतिहास",
    farmerAccount: "किसान खाता",
    signOut: "साइन आउट",
    deleteScan: "स्कैन हटाएं",
    fullName: "पूरा नाम",
    noAnalysis: "अभी तक कोई विश्लेषण नहीं",
    noAnalysisDesc: "AI-संचालित स्वास्थ्य अंतर्दृष्टि देखने के लिए यहां एक पत्ती की फोटो अपलोड करें।",
    analysisError: "विश्लेषण त्रुटि",
    tryAgain: "पुनः प्रयास करें",
    footerText: "यह AI उपकरण केवल सूचनात्मक उद्देश्यों के लिए है। महत्वपूर्ण निर्णयों के लिए हमेशा स्थानीय कृषि विशेषज्ञ से परामर्श करें।",
    errorGeneric: "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    errorGoogle: "गूगल के साथ साइन इन करने में विफल।",
    errorEmailInUse: "यह ईमेल पहले से ही पंजीकृत है।",
    errorInvalidCreds: "अमान्य ईमेल या पासवर्ड।",
    errorWeakPassword: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    errorAuth: "प्रमाणीकरण विफल रहा। कृपया अपने विवरण की जाँच करें।",
    errorChatbot: "मुझे अपने ज्ञान आधार से जुड़ने में समस्या हो रही है। कृपया पुनः प्रयास करें।",
    errorChatbotFallback: "क्षमा करें, मैं उसे संसाधित नहीं कर सका।",
    errorAnalysis: "छवि का विश्लेषण करने में विफल। कृपया स्पष्ट फोटो के साथ पुनः प्रयास करें।",
    chatContext: (d: string, s: string, t: string) => `वर्तमान स्कैन ${s} गंभीरता के साथ ${d} दिखाता है। उपचार: ${t}।`,
    chatNoContext: "अभी तक कोई स्कैन नहीं किया गया है।",
    steps: [
      "छवि संसाधित",
      "धब्बों का पता चला",
      "पैटर्न मेल खाया",
      "रोग की पहचान हुई",
      "उपचार का सुझाव दिया गया"
    ],
    voiceImproving: "आपकी फसल की स्थिति में सुधार हो रहा है!",
    voiceWorsening: "चेतावनी: बीमारी फैल रही है। कृपया तुरंत कार्रवाई करें।",
    voiceRecovered: "आपकी फसल पूरी तरह से ठीक हो गई है!",
    voiceInitial: "प्रारंभिक निदान पूरा हुआ।",
    timeline: "समयरेखा",
    progress: "प्रगति",
    improving: "सुधार",
    worsening: "बिगड़ रहा है",
    recovered: "ठीक हो गया",
    initial: "प्रारंभिक",
    voiceMode: "वॉयस मोड",
    voiceModeDesc: "ऐप प्रगति अपडेट बोलेगा"
  }
};

export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [authMode, setAuthMode] = useState<'login' | 'register' | 'google'>('login');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [image, setImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [history, setHistory] = useState<AnalysisResult[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  const [showTimeline, setShowTimeline] = useState(false);
  const [favoritesOnly, setFavoritesOnly] = useState(false);
  const [voiceModeEnabled, setVoiceModeEnabled] = useState(true);
  const [language, setLanguage] = useState<'en' | 'ta' | 'hi'>(() => {
    const saved = localStorage.getItem('cropguard_lang');
    return (saved as any) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('cropguard_lang', language);
  }, [language]);

  // Translation helper
  const t = (key: keyof typeof translations['en']): any => {
    return (translations[language] as any)[key] || (translations['en'] as any)[key];
  };
  
  // Pro Features State
  const [isCameraOpen, setIsCameraOpen] = useState(false);
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const [analysisSteps, setAnalysisSteps] = useState<AnalysisStep[]>([
    { id: 'process', label: t('steps')[0], status: 'pending' },
    { id: 'spots', label: t('steps')[1], status: 'pending' },
    { id: 'pattern', label: t('steps')[2], status: 'pending' },
    { id: 'identify', label: t('steps')[3], status: 'pending' },
    { id: 'treatment', label: t('steps')[4], status: 'pending' },
  ]);
  const [currentStepIndex, setCurrentStepIndex] = useState(-1);

  useEffect(() => {
    // Update analysis steps labels when language changes
    setAnalysisSteps(steps => steps.map((s, i) => ({ ...s, label: t('steps')[i] })));
  }, [language]);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setUser(user);
      setAuthLoading(false);
    });
    return () => unsubscribe();
  }, []);

  useEffect(() => {
    if (!user) {
      setHistory([]);
      return;
    }

    const q = query(
      collection(db, "scans"),
      where("userId", "==", user.uid),
      orderBy("createdAt", "desc")
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const scans = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      } as AnalysisResult));
      setHistory(scans);
    });

    return () => unsubscribe();
  }, [user]);

  const handleGoogleLogin = async () => {
    try {
      await signInWithPopup(auth, googleProvider);
    } catch (err) {
      console.error("Google login failed:", err);
      setError(t('errorGoogle'));
    }
  };

  const handleEmailAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    try {
      if (authMode === 'register') {
        const userCredential = await createUserWithEmailAndPassword(auth, email, password);
        await updateProfile(userCredential.user, { displayName });
      } else {
        await signInWithEmailAndPassword(auth, email, password);
      }
    } catch (err: any) {
      console.error("Email auth failed:", err);
      if (err.code === 'auth/email-already-in-use') {
        setError(t('errorEmailInUse'));
      } else if (err.code === 'auth/invalid-credential') {
        setError(t('errorInvalidCreds'));
      } else if (err.code === 'auth/weak-password') {
        setError(t('errorWeakPassword'));
      } else {
        setError(t('errorAuth'));
      }
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = async () => {
    try {
      await signOut(auth);
      reset();
      stopCamera();
    } catch (err) {
      console.error("Logout failed:", err);
    }
  };

  // Camera Logic
  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
      setIsCameraOpen(true);
      setError(null);
    } catch (err) {
      console.error("Camera access failed:", err);
      setError("Failed to access camera. Please ensure permissions are granted.");
    }
  };

  const stopCamera = () => {
    if (videoRef.current?.srcObject) {
      const tracks = (videoRef.current.srcObject as MediaStream).getTracks();
      tracks.forEach(track => track.stop());
      videoRef.current.srcObject = null;
    }
    setIsCameraOpen(false);
  };

  const capturePhoto = () => {
    if (videoRef.current && canvasRef.current) {
      const video = videoRef.current;
      const canvas = canvasRef.current;
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
        const dataUrl = canvas.toDataURL('image/jpeg');
        setImage(dataUrl);
        stopCamera();
        setResult(null);
        setError(null);
      }
    }
  };

  // Chatbot Logic
  const sendMessageToChatbot = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!chatInput.trim() || isChatLoading) return;

    const userMsg = chatInput.trim();
    setChatMessages(prev => [...prev, { role: 'user', text: userMsg }]);
    setChatInput('');
    setIsChatLoading(true);

    try {
      const severityText = result ? (result.severity === 'High' ? t('high') : result.severity === 'Medium' ? t('medium') : t('low')) : '';
      const context = result ? t('chatContext')(result.disease, severityText, result.solution) : t('chatNoContext');
      const langName = language === 'ta' ? 'Tamil' : language === 'hi' ? 'Hindi' : 'English';
      const langPrompt = language === 'ta' ? 'தமிழில் மட்டும் பதில் அளிக்கவும்.' : language === 'hi' ? 'केवल हिंदी में उत्तर दें।' : 'Respond only in English.';
      
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: [
          { role: 'user', parts: [{ text: `Context: ${context}\n\nUser Question: ${userMsg}\n\n${langPrompt}` }] }
        ],
        config: {
          systemInstruction: `You are a helpful agricultural expert chatbot for CropGuard AI. Answer questions about crop diseases, farming tips, and plant health. Be concise and professional. You MUST respond in ${langName}. Always provide your response in a clear, point-wise (bulleted) format using bullet points (•) for each point to ensure better readability. Do not use bold characters for bullets.`
        }
      });

      setChatMessages(prev => [...prev, { role: 'model', text: response.text || t('errorChatbotFallback') }]);
      
      // Speak the response if voice mode is enabled
      if (voiceModeEnabled && response.text) {
        handleVoiceExplanation(response.text.replace(/•/g, ''));
      }
    } catch (err) {
      console.error("Chatbot failed:", err);
      setChatMessages(prev => [...prev, { role: 'model', text: t('errorChatbot') }]);
    } finally {
      setIsChatLoading(false);
    }
  };

  // Voice Explanation
  const speakResult = () => {
    if (!result || isSpeaking) return;

    const severityText = result.severity === 'High' ? t('high') : result.severity === 'Medium' ? t('medium') : t('low');
    const textToSpeak = t('voiceTemplate')(result.disease, result.confidence, severityText, result.solution);
    
    handleVoiceExplanation(textToSpeak);
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result as string);
        setResult(null);
        setError(null);
      };
      reader.readAsDataURL(file);
    }
  };

  const analyzeImage = async () => {
    if (!image || !user) return;

    setLoading(true);
    setError(null);
    setCurrentStepIndex(0);
    setAnalysisSteps(steps => steps.map((s, i) => ({ ...s, label: t('steps')[i], status: 'pending' })));

    const updateStep = (index: number, status: 'loading' | 'completed') => {
      setAnalysisSteps(prev => prev.map((s, i) => i === index ? { ...s, status } : s));
    };

    try {
      // Step 1: Image processed
      updateStep(0, 'loading');
      await new Promise(r => setTimeout(r, 800));
      updateStep(0, 'completed');
      setCurrentStepIndex(1);

      // Step 2: Spots detected
      updateStep(1, 'loading');
      await new Promise(r => setTimeout(r, 1000));
      updateStep(1, 'completed');
      setCurrentStepIndex(2);

      // Step 3: Pattern matched
      updateStep(2, 'loading');
      
      const base64Data = image.split(',')[1];
      const langName = language === 'ta' ? 'Tamil' : language === 'hi' ? 'Hindi' : 'English';
      
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: {
          parts: [
            {
              inlineData: {
                mimeType: "image/jpeg",
                data: base64Data,
              },
            },
            {
              text: `Analyze this crop leaf image for diseases. Detect multiple diseases if present. Provide the following information in JSON format: disease (name), severity (Low/Medium/High), confidence (percentage), solution (brief treatment), details (more explanation), and highlights (array of objects with box_2d [ymin, xmin, ymax, xmax] and label). If no disease is found, state 'Healthy' for disease and 'Low' for severity. 

CRITICAL: You MUST provide all text fields (disease, solution, details, and labels in the highlights) in ${langName}. 
- DO NOT use English for these fields. 
- Translate or transliterate EVERYTHING to ${langName}. 
- Even the disease name MUST be in ${langName}. 
- If ${langName} is Tamil, use ONLY Tamil characters. 
- If ${langName} is Hindi, use ONLY Hindi characters.
- IMPORTANT: Provide 'solution' and 'details' in a clear, point-wise (bulleted) format using bullet points (•).`,
            },
          ],
        },
        config: {
          systemInstruction: `You are a world-class agricultural pathologist. Your task is to identify crop diseases from images. You must respond in ${langName} for all descriptive fields.`,
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              disease: { type: Type.STRING },
              severity: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
              confidence: { type: Type.STRING },
              solution: { type: Type.STRING },
              details: { type: Type.STRING },
              highlights: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    box_2d: { type: Type.ARRAY, items: { type: Type.NUMBER } },
                    label: { type: Type.STRING }
                  }
                }
              }
            },
            required: ["disease", "severity", "confidence", "solution", "details"],
          },
        },
      });

      updateStep(2, 'completed');
      setCurrentStepIndex(3);

      // Step 4: Disease identified
      updateStep(3, 'loading');
      const data = JSON.parse(response.text || '{}');
      await new Promise(r => setTimeout(r, 500));
      updateStep(3, 'completed');
      setCurrentStepIndex(4);

      // Step 5: Treatment suggested
      updateStep(4, 'loading');
      
      // Determine progress status
      let progressStatus: 'initial' | 'improving' | 'worsening' | 'recovered' = 'initial';
      let voiceFeedback = t('voiceInitial');

      const isHealthy = 
        data.disease.toLowerCase().includes('healthy') || 
        data.disease.includes('ஆரோக்கியமானது') || 
        data.disease.includes('स्वस्थ') ||
        data.disease.includes('ஆரோக்கியம்') ||
        data.disease.includes('सेहतमंद');

      if (history.length > 0) {
        const lastScan = history[0]; // history is sorted by date desc
        const wasHealthy = 
          lastScan.disease.toLowerCase().includes('healthy') || 
          lastScan.disease.includes('ஆரோக்கியமானது') || 
          lastScan.disease.includes('स्वस्थ') ||
          lastScan.disease.includes('ஆரோக்கியம்') ||
          lastScan.disease.includes('सेहतमंद');

        if (!wasHealthy && isHealthy) {
          progressStatus = 'recovered';
          voiceFeedback = t('voiceRecovered');
        } else if (!wasHealthy && !isHealthy) {
          const severityMap = { 'Low': 1, 'Medium': 2, 'High': 3 };
          const currentSev = severityMap[data.severity as keyof typeof severityMap] || 0;
          const lastSev = severityMap[lastScan.severity as keyof typeof severityMap] || 0;

          if (currentSev < lastSev) {
            progressStatus = 'improving';
            voiceFeedback = t('voiceImproving');
          } else if (currentSev > lastSev) {
            progressStatus = 'worsening';
            voiceFeedback = t('voiceWorsening');
          } else {
            progressStatus = 'initial';
            voiceFeedback = t('voiceInitial');
          }
        }
      }

      const analysisResult: AnalysisResult = { 
        ...data, 
        imageUrl: image, 
        isFavorite: false,
        progressStatus 
      };
      
      await new Promise(r => setTimeout(r, 500));
      updateStep(4, 'completed');

      setResult(analysisResult);

      // Save to Firestore
      const docRef = await addDoc(collection(db, "scans"), {
        ...analysisResult,
        userId: user.uid,
        createdAt: serverTimestamp()
      });
      
      setResult({ ...analysisResult, id: docRef.id });

      // Voice Feedback
      if (voiceModeEnabled) {
        handleVoiceExplanation(voiceFeedback);
      }

    } catch (err) {
      console.error("Analysis failed:", err);
      setError(t('errorAnalysis'));
    } finally {
      setLoading(false);
      setCurrentStepIndex(-1);
    }
  };

  const handleVoiceExplanation = (text: string) => {
    if (!('speechSynthesis' in window)) return;
    
    // Cancel any ongoing speech
    window.speechSynthesis.cancel();
    
    const utterance = new SpeechSynthesisUtterance(text);
    
    // Set language based on app language
    if (language === 'ta') utterance.lang = 'ta-IN';
    else if (language === 'hi') utterance.lang = 'hi-IN';
    else utterance.lang = 'en-US';
    
    utterance.rate = 0.9; // Slightly slower for clarity
    utterance.pitch = 1;
    
    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);
    
    window.speechSynthesis.speak(utterance);
  };

  const startSpeechRecognition = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      setError("Speech recognition is not supported in this browser.");
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.lang = language === 'ta' ? 'ta-IN' : language === 'hi' ? 'hi-IN' : 'en-US';
    recognition.interimResults = false;
    recognition.maxAlternatives = 1;

    recognition.onstart = () => setIsListening(true);
    recognition.onend = () => setIsListening(false);
    recognition.onerror = () => setIsListening(false);

    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript;
      setChatInput(transcript);
    };

    recognition.start();
  };

  const toggleFavorite = async (scan: AnalysisResult) => {
    if (!scan.id) return;
    try {
      const scanRef = doc(db, "scans", scan.id);
      await updateDoc(scanRef, {
        isFavorite: !scan.isFavorite
      });
      if (result && result.id === scan.id) {
        setResult({ ...result, isFavorite: !scan.isFavorite });
      }
    } catch (err) {
      console.error("Failed to toggle favorite:", err);
    }
  };

  const deleteScan = async (id: string) => {
    try {
      await deleteDoc(doc(db, "scans", id));
      if (result && result.id === id) {
        setResult(null);
        setImage(null);
      }
    } catch (err) {
      console.error("Failed to delete scan:", err);
    }
  };

  const getHighlightedImage = async (imgSrc: string, result: AnalysisResult): Promise<string> => {
    return new Promise((resolve) => {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          resolve(imgSrc);
          return;
        }

        // Draw original image
        ctx.drawImage(img, 0, 0);

        // Draw highlights
        if (result.highlights && result.highlights.length > 0) {
          result.highlights.forEach(h => {
            const [ymin, xmin, ymax, xmax] = h.box_2d;
            
            // Gemini coordinates are 0-1000
            const left = (xmin / 1000) * img.width;
            const top = (ymin / 1000) * img.height;
            const width = ((xmax - xmin) / 1000) * img.width;
            const height = ((ymax - ymin) / 1000) * img.height;

            // Box
            ctx.strokeStyle = '#ef4444'; // red-500
            ctx.lineWidth = Math.max(2, img.width / 200);
            ctx.strokeRect(left, top, width, height);

            // Label background
            ctx.fillStyle = '#ef4444';
            const fontSize = Math.max(12, img.width / 40);
            ctx.font = `bold ${fontSize}px sans-serif`;
            const labelWidth = ctx.measureText(h.label).width;
            ctx.fillRect(left, top - fontSize - 4, labelWidth + 8, fontSize + 4);

            // Label text
            ctx.fillStyle = '#ffffff';
            ctx.fillText(h.label, left + 4, top - 4);
          });
        }

        resolve(canvas.toDataURL('image/jpeg', 0.8));
      };
      img.onerror = () => resolve(imgSrc);
      img.src = imgSrc;
    });
  };

  const downloadPDF = async (data: AnalysisResult, img: string) => {
    setIsGeneratingPDF(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      let y = 20;

      doc.setFontSize(22);
      doc.setTextColor(22, 101, 52);
      doc.text(t('pdfTitle'), margin, y);
      y += 5;

      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text(`${t('pdfGeneratedOn')}: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, margin, y);
      y += 7;

      try {
        const highlightedImg = await getHighlightedImage(img, data);
        const imgProps = doc.getImageProperties(highlightedImg);
        const imgWidth = pageWidth - (margin * 2);
        const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
        const maxHeight = 80;
        const finalImgHeight = Math.min(imgHeight, maxHeight);
        const finalImgWidth = (imgProps.width * finalImgHeight) / imgProps.height;
        doc.addImage(highlightedImg, 'JPEG', margin + (imgWidth - finalImgWidth) / 2, y, finalImgWidth, finalImgHeight);
        y += finalImgHeight + 8;
      } catch (e) {
        y += 10;
      }

      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
      doc.text(`${t('pdfDiagnosis')}:`, margin, y);
      y += 5;
      doc.setFontSize(18);
      if (data.disease.toLowerCase().includes('healthy') || data.disease.includes('ஆரோக்கியமானது') || data.disease.includes('स्वस्थ')) {
        doc.setTextColor(22, 163, 74);
      } else {
        doc.setTextColor(220, 38, 38);
      }
      const severityText = data.severity === 'High' ? t('high') : data.severity === 'Medium' ? t('medium') : t('low');
      doc.text(`${data.disease} (${severityText} ${t('severity')})`, margin, y);
      y += 8;

      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text(`${t('confidence')}: ${data.confidence}`, margin, y);
      y += 8;

      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
      doc.text(`${t('pdfTreatment')}:`, margin, y);
      y += 5;
      doc.setFontSize(11);
      doc.setTextColor(51, 65, 85);
      const solutionLines = doc.splitTextToSize(data.solution.replace(/[*]/g, '•').replace(/[#`]/g, ''), pageWidth - (margin * 2));
      solutionLines.forEach((line: string) => {
        if (y + 7 > doc.internal.pageSize.getHeight() - 20) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, margin, y);
        y += 6;
        if (line.trim().startsWith('•')) y += 2; // Extra space after each point
      });
      y += 10;

      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
      doc.text(`${t('pdfAnalysisDetails')}:`, margin, y);
      y += 5;
      doc.setFontSize(10);
      doc.setTextColor(71, 85, 105);
      const detailLines = doc.splitTextToSize(data.details.replace(/[*]/g, '•').replace(/[#`]/g, ''), pageWidth - (margin * 2));
      detailLines.forEach((line: string) => {
        if (y + 6 > doc.internal.pageSize.getHeight() - 20) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, margin, y);
        y += 5;
        if (line.trim().startsWith('•')) y += 3; // Extra space after each point
      });
      y += 15;

      // Add Chat Expert Consultation
      if (chatMessages.length > 0) {
        if (y > doc.internal.pageSize.getHeight() - 40) {
          doc.addPage();
          y = 20;
        }
        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text(`${t('askExpert')}:`, margin, y);
        y += 7;
        
        chatMessages.forEach((msg) => {
          doc.setFontSize(9);
          doc.setTextColor(msg.role === 'user' ? 71 : 22, msg.role === 'user' ? 85 : 101, msg.role === 'user' ? 105 : 52);
          const roleLabel = msg.role === 'user' ? 'User' : 'Expert';
          const msgLines = doc.splitTextToSize(`${roleLabel}: ${msg.text.replace(/[*]/g, '•').replace(/[#`]/g, '')}`, pageWidth - (margin * 2));
          
          msgLines.forEach((line: string) => {
            if (y + 6 > doc.internal.pageSize.getHeight() - 20) {
              doc.addPage();
              y = 20;
            }
            doc.text(line, margin, y);
            y += 5;
            if (line.trim().startsWith('•')) y += 3; // Extra space after each point
          });
          y += 5; // Space between messages
        });
      }

      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(t('pdfFooter'), margin, doc.internal.pageSize.getHeight() - 10);

      doc.save(`${t('pdfFilename')}_${data.disease.replace(/\s+/g, '_')}.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const reset = () => {
    setImage(null);
    setResult(null);
    setError(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  if (authLoading) {
    return (
      <div className="min-h-screen bg-[#F8F9FA] flex items-center justify-center">
        <div className="w-10 h-10 border-4 border-green-200 border-t-green-600 rounded-full animate-spin" />
      </div>
    );
  }

  if (!user) {
    return (
      <div className="min-h-screen bg-[#F8F9FA] flex flex-col items-center justify-center p-4">
        <div className="absolute top-6 right-6">
          <select 
            value={language}
            onChange={(e) => setLanguage(e.target.value as any)}
            className="bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm font-bold shadow-sm outline-none focus:ring-2 focus:ring-green-500 transition-all"
          >
            <option value="en">English</option>
            <option value="ta">தமிழ்</option>
            <option value="hi">हिन्दी</option>
          </select>
        </div>

        <motion.div 
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-white rounded-3xl shadow-xl border border-gray-200 p-8 max-w-md w-full"
        >
          <div className="text-center mb-8">
            <div className="bg-green-600 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg shadow-green-200">
              <Leaf className="text-white w-8 h-8" />
            </div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">{t('appName')}</h1>
            <p className="text-gray-500">
              {authMode === 'login' ? t('welcome') : authMode === 'register' ? t('join') : t('chooseAuth')}
            </p>
          </div>

          <AnimatePresence mode="wait">
            {authMode === 'login' || authMode === 'register' ? (
              <motion.form 
                key="email-form"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                onSubmit={handleEmailAuth}
                className="space-y-4"
              >
                {authMode === 'register' && (
                  <div className="relative">
                    <UserIcon className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                    <input 
                      type="text" 
                      placeholder={t('fullName')}
                      required
                      value={displayName}
                      onChange={(e) => setDisplayName(e.target.value)}
                      className="w-full pl-12 pr-4 py-4 bg-gray-50 border border-gray-200 rounded-2xl focus:ring-2 focus:ring-green-500 focus:border-transparent outline-none transition-all"
                    />
                  </div>
                )}
                <div className="relative">
                  <Mail className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input 
                    type="email" 
                    placeholder={t('email')}
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full pl-12 pr-4 py-4 bg-gray-50 border border-gray-200 rounded-2xl focus:ring-2 focus:ring-green-500 focus:border-transparent outline-none transition-all"
                  />
                </div>
                <div className="relative">
                  <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input 
                    type="password" 
                    placeholder={t('password')}
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="w-full pl-12 pr-4 py-4 bg-gray-50 border border-gray-200 rounded-2xl focus:ring-2 focus:ring-green-500 focus:border-transparent outline-none transition-all"
                  />
                </div>

                {error && (
                  <div className="bg-red-50 text-red-600 text-sm p-3 rounded-xl flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 shrink-0" />
                    {error}
                  </div>
                )}

                <button 
                  type="submit"
                  disabled={loading}
                  className="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-4 rounded-2xl shadow-lg shadow-green-100 transition-all flex items-center justify-center gap-2 disabled:opacity-50 active:scale-[0.98]"
                >
                  {loading ? <RefreshCw className="w-5 h-5 animate-spin" /> : (authMode === 'login' ? t('signIn') : t('createAccount'))}
                  <ArrowRight className="w-5 h-5" />
                </button>

                <div className="relative py-4">
                  <div className="absolute inset-0 flex items-center"><div className="w-full border-t border-gray-100"></div></div>
                  <div className="relative flex justify-center text-xs uppercase"><span className="bg-white px-2 text-gray-400 font-bold">{t('or')}</span></div>
                </div>

                <button 
                  type="button"
                  onClick={handleGoogleLogin}
                  className="w-full bg-white border-2 border-gray-200 hover:border-green-600 hover:bg-green-50 text-gray-700 font-bold py-4 rounded-2xl transition-all flex items-center justify-center gap-3 active:scale-[0.98]"
                >
                  <img src="https://www.google.com/favicon.ico" alt="Google" className="w-5 h-5" />
                  {t('continueWithGoogle')}
                </button>

                <p className="text-center text-sm text-gray-500 pt-4">
                  {authMode === 'login' ? (
                    <>{t('noAccount')} <button type="button" onClick={() => { setAuthMode('register'); setError(null); }} className="text-green-600 font-bold hover:underline">{t('register')}</button></>
                  ) : (
                    <>{t('hasAccount')} <button type="button" onClick={() => { setAuthMode('login'); setError(null); }} className="text-green-600 font-bold hover:underline">{t('login')}</button></>
                  )}
                </p>
              </motion.form>
            ) : null}
          </AnimatePresence>
          
          <p className="text-[10px] text-gray-400 mt-8 text-center leading-relaxed">
            {t('terms')} <br />
            {t('poweredBy')}
          </p>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#F8F9FA] text-[#212529] font-sans selection:bg-green-100">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-green-600 p-2 rounded-lg">
              <Leaf className="text-white w-5 h-5" />
            </div>
            <h1 className="font-bold text-xl tracking-tight text-gray-900">{t("title")}</h1>
          </div>
          
          <div className="flex items-center gap-4">
            <select 
              value={language}
              onChange={(e) => setLanguage(e.target.value as any)}
              className="bg-gray-50 border border-gray-200 rounded-lg px-2 py-1.5 text-xs font-bold outline-none focus:ring-2 focus:ring-green-500"
            >
              <option value="en">English</option>
              <option value="ta">தமிழ்</option>
              <option value="hi">हिन्दी</option>
            </select>
            <button 
              onClick={() => setVoiceModeEnabled(!voiceModeEnabled)}
              className={`p-2 rounded-lg transition-colors ${voiceModeEnabled ? 'text-green-600 bg-green-50' : 'text-gray-400 hover:bg-gray-100'}`}
              title={t('voiceMode')}
            >
              <Mic className={`w-5 h-5 ${voiceModeEnabled && 'animate-pulse'}`} />
            </button>
            <button 
              onClick={() => setShowHistory(!showHistory)}
              className={`p-2 rounded-lg transition-colors ${showHistory ? 'bg-green-100 text-green-600' : 'text-gray-500 hover:bg-gray-100'}`}
              title={t('history')}
            >
              <History className="w-5 h-5" />
            </button>
            <div className="flex items-center gap-3 pl-4 border-l border-gray-200">
              <div className="hidden sm:block text-right">
                <p className="text-xs font-bold text-gray-900 leading-none">{user.displayName || user.email?.split('@')[0]}</p>
                <p className="text-[10px] text-gray-400 mt-1">{t('farmerAccount')}</p>
              </div>
              <button 
                onClick={handleLogout}
                className="p-2 text-gray-400 hover:text-red-500 transition-colors"
                title={t('signOut')}
              >
                <LogOut className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8 md:py-12">
        <AnimatePresence mode="wait">
          {showHistory ? (
            <motion.div 
              key="history"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-6"
            >
              <div className="flex items-center justify-between">
                <h2 className="text-2xl font-bold text-gray-900">{t('scanHistory')}</h2>
                <div className="flex items-center gap-4">
                  <div className="flex bg-gray-100 p-1 rounded-xl">
                    <button 
                      onClick={() => setShowTimeline(false)}
                      className={`p-1.5 rounded-lg transition-all ${!showTimeline ? 'bg-white shadow-sm text-green-600' : 'text-gray-400'}`}
                      title="Grid View"
                    >
                      <LayoutGrid className="w-4 h-4" />
                    </button>
                    <button 
                      onClick={() => setShowTimeline(true)}
                      className={`p-1.5 rounded-lg transition-all ${showTimeline ? 'bg-white shadow-sm text-green-600' : 'text-gray-400'}`}
                      title="Timeline View"
                    >
                      <Activity className="w-4 h-4" />
                    </button>
                  </div>
                  <button 
                    onClick={() => setFavoritesOnly(!favoritesOnly)}
                    className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-bold transition-all ${favoritesOnly ? 'bg-yellow-100 text-yellow-700 border-yellow-200' : 'bg-gray-100 text-gray-500 border-gray-200'} border`}
                  >
                    <Star className={`w-4 h-4 ${favoritesOnly ? 'fill-yellow-500' : ''}`} />
                    {favoritesOnly ? t('favorites') : t('allScans')}
                  </button>
                  <button 
                    onClick={() => setShowHistory(false)}
                    className="text-sm font-bold text-green-600 hover:text-green-700"
                  >
                    {t('backToScanner')}
                  </button>
                </div>
              </div>

              {history.filter(item => !favoritesOnly || item.isFavorite).length === 0 ? (
                <div className="bg-white rounded-3xl border border-dashed border-gray-200 p-12 text-center">
                  <History className="w-12 h-12 text-gray-200 mx-auto mb-4" />
                  <p className="text-gray-400">
                    {favoritesOnly ? t('noFavorites') : t('noScans')}
                  </p>
                </div>
              ) : showTimeline ? (
                <div className="relative space-y-8 before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-gray-200 before:to-transparent">
                  {history
                    .filter(item => !favoritesOnly || item.isFavorite)
                    .sort((a, b) => (b.createdAt?.toMillis() || 0) - (a.createdAt?.toMillis() || 0))
                    .map((item, idx) => (
                      <motion.div 
                        key={item.id || idx}
                        initial={{ opacity: 0, x: idx % 2 === 0 ? -20 : 20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group"
                      >
                        {/* Dot */}
                        <div className="flex items-center justify-center w-10 h-10 rounded-full border border-white bg-white shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 z-10">
                          <div className={`w-3 h-3 rounded-full ${
                            item.progressStatus === 'recovered' ? 'bg-green-500' :
                            item.progressStatus === 'improving' ? 'bg-blue-500' :
                            item.progressStatus === 'worsening' ? 'bg-red-500' :
                            'bg-gray-400'
                          }`} />
                        </div>

                        {/* Content */}
                        <div className="w-[calc(100%-4rem)] md:w-[45%] bg-white p-4 rounded-2xl border border-gray-200 shadow-sm hover:shadow-md transition-shadow cursor-pointer"
                          onClick={() => {
                            setResult(item);
                            setImage(item.imageUrl || null);
                            setShowHistory(false);
                          }}
                        >
                          <div className="flex items-center justify-between mb-2">
                            <time className="text-xs font-bold text-green-600">
                              {item.createdAt?.toDate().toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                            </time>
                            <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider ${
                              item.progressStatus === 'recovered' ? 'bg-green-100 text-green-700' :
                              item.progressStatus === 'improving' ? 'bg-blue-100 text-blue-700' :
                              item.progressStatus === 'worsening' ? 'bg-red-100 text-red-700' :
                              'bg-gray-100 text-gray-600'
                            }`}>
                              {t(item.progressStatus || 'initial')}
                            </span>
                          </div>
                          <div className="flex gap-4">
                            <img src={item.imageUrl} alt="" className="w-16 h-16 rounded-lg object-cover bg-gray-100" />
                            <div className="flex-1 min-w-0">
                              <h4 className="font-bold text-gray-900 truncate">{item.disease}</h4>
                              <p className="text-xs text-gray-500 mt-1 line-clamp-2">{item.solution}</p>
                            </div>
                          </div>
                          <div className="mt-3 flex items-center justify-between">
                            <div className="flex items-center gap-2">
                              <div className="w-24 h-1.5 bg-gray-100 rounded-full overflow-hidden">
                                <div className="h-full bg-green-500" style={{ width: item.confidence }} />
                              </div>
                              <span className="text-[10px] font-bold text-gray-400">{item.confidence}</span>
                            </div>
                            <button 
                              onClick={(e) => {
                                e.stopPropagation();
                                deleteScan(item.id!);
                              }}
                              className="text-gray-300 hover:text-red-500 transition-colors"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                      </motion.div>
                    ))}
                </div>
              ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {history.filter(item => !favoritesOnly || item.isFavorite).map((item, idx) => (
                    <motion.div 
                      key={item.id || idx}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: idx * 0.05 }}
                      className="bg-white rounded-2xl border border-gray-200 overflow-hidden hover:shadow-md transition-shadow cursor-pointer group relative"
                    >
                      <button 
                        onClick={(e) => {
                          e.stopPropagation();
                          toggleFavorite(item);
                        }}
                        className="absolute top-2 right-2 z-10 p-2 bg-white/80 backdrop-blur rounded-full shadow-sm hover:bg-white transition-all"
                      >
                        <Star className={`w-4 h-4 ${item.isFavorite ? 'fill-yellow-500 text-yellow-500' : 'text-gray-400'}`} />
                      </button>
                      <div 
                        className="flex gap-4 p-4"
                        onClick={() => {
                          setResult(item);
                          setImage(item.imageUrl || null);
                          setShowHistory(false);
                        }}
                      >
                        <div className="w-20 h-20 rounded-xl bg-gray-100 overflow-hidden shrink-0">
                          <img src={item.imageUrl} alt="" className="w-full h-full object-cover" />
                        </div>
                        <div className="flex flex-col justify-center overflow-hidden">
                          <h4 className="font-bold text-gray-900 truncate">{item.disease}</h4>
                          <p className="text-xs text-gray-400 mt-1">
                            {item.createdAt?.toDate().toLocaleDateString()} • {item.confidence}
                          </p>
                          <span className={`text-[10px] font-bold uppercase tracking-wider mt-2 ${item.disease.toLowerCase().includes('healthy') || item.disease.includes('ஆரோக்கியமானது') || item.disease.includes('स्वस्थ') ? 'text-green-600' : 'text-red-500'}`}>
                            {item.disease.toLowerCase().includes('healthy') || item.disease.includes('ஆரோக்கியமானது') || item.disease.includes('स्वस्थ') ? t('healthy') : t('diseased')}
                          </span>
                        </div>
                      </div>
                      <button 
                        onClick={(e) => {
                          e.stopPropagation();
                          deleteScan(item.id!);
                        }}
                        className="absolute bottom-2 right-2 p-2 text-gray-300 hover:text-red-500 transition-colors opacity-0 group-hover:opacity-100"
                        title={t('deleteScan')}
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </motion.div>
                  ))}
                </div>
              )}
            </motion.div>
          ) : (
            <motion.div 
              key="scanner"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start"
            >
              {/* Left Column: Upload & Preview */}
              <div className="space-y-6">
                <section className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
                  <div className="p-6">
                    <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                      <Camera className="w-5 h-5 text-green-600" />
                      {t("captureUpload")}
                    </h2>
                    
                    {!image && !isCameraOpen ? (
                      <div className="grid grid-cols-2 gap-4">
                        <div 
                          onClick={() => fileInputRef.current?.click()}
                          className="border-2 border-dashed border-gray-300 rounded-xl p-8 flex flex-col items-center justify-center gap-4 cursor-pointer hover:border-green-500 hover:bg-green-50 transition-all group"
                        >
                          <Upload className="w-8 h-8 text-gray-400 group-hover:text-green-600" />
                          <p className="text-sm font-medium text-gray-700">{t("upload")}</p>
                        </div>
                        <div 
                          onClick={startCamera}
                          className="border-2 border-dashed border-gray-300 rounded-xl p-8 flex flex-col items-center justify-center gap-4 cursor-pointer hover:border-green-500 hover:bg-green-50 transition-all group"
                        >
                          <Camera className="w-8 h-8 text-gray-400 group-hover:text-green-600" />
                          <p className="text-sm font-medium text-gray-700">{t("camera")}</p>
                        </div>
                      </div>
                    ) : isCameraOpen ? (
                      <div className="relative rounded-xl overflow-hidden bg-black aspect-square flex items-center justify-center">
                        <video 
                          ref={videoRef} 
                          autoPlay 
                          playsInline 
                          className="w-full h-full object-cover"
                        />
                        <div className="absolute bottom-6 left-0 right-0 flex justify-center gap-4">
                          <button 
                            onClick={capturePhoto}
                            className="bg-white p-4 rounded-full shadow-xl active:scale-90 transition-transform"
                          >
                            <div className="w-8 h-8 rounded-full border-4 border-green-600" />
                          </button>
                          <button 
                            onClick={stopCamera}
                            className="bg-red-500 p-4 rounded-full shadow-xl text-white active:scale-90 transition-transform"
                          >
                            <X className="w-6 h-6" />
                          </button>
                        </div>
                      </div>
                    ) : (
                      <div className="relative rounded-xl overflow-hidden bg-black aspect-square flex items-center justify-center">
                        <img 
                          src={image!} 
                          alt="Leaf preview" 
                          className="max-h-full object-contain"
                          referrerPolicy="no-referrer"
                        />
                        {result?.highlights && (
                          <div className="absolute inset-0 pointer-events-none">
                            {result.highlights.map((h, i) => (
                              <div 
                                key={i}
                                className="absolute border-2 border-red-500 bg-red-500/20 rounded"
                                style={{
                                  top: `${h.box_2d[0] / 10}%`,
                                  left: `${h.box_2d[1] / 10}%`,
                                  height: `${(h.box_2d[2] - h.box_2d[0]) / 10}%`,
                                  width: `${(h.box_2d[3] - h.box_2d[1]) / 10}%`,
                                }}
                              >
                                <span className="absolute -top-6 left-0 bg-red-500 text-white text-[10px] px-1 rounded font-bold whitespace-nowrap">
                                  {h.label}
                                </span>
                              </div>
                            ))}
                          </div>
                        )}
                        <button 
                          onClick={reset}
                          className="absolute top-4 right-4 bg-white/90 backdrop-blur shadow-lg p-2 rounded-full hover:bg-white transition-colors"
                        >
                          <RefreshCw className="w-5 h-5 text-gray-700" />
                        </button>
                      </div>
                    )}
                    <canvas ref={canvasRef} className="hidden" />

                    <input 
                      type="file" 
                      ref={fileInputRef}
                      onChange={handleImageUpload}
                      accept="image/*"
                      className="hidden"
                    />

                    {image && !result && !loading && (
                      <button 
                        onClick={analyzeImage}
                        className="w-full mt-6 bg-green-600 hover:bg-green-700 text-white font-bold py-4 rounded-xl shadow-lg shadow-green-200 transition-all flex items-center justify-center gap-2 active:scale-[0.98]"
                      >
                        <Leaf className="w-5 h-5" />
                        {t("analyze")}
                      </button>
                    )}

                    {loading && (
                      <div className="mt-6 space-y-4">
                        {analysisSteps.map((step, idx) => (
                          <motion.div 
                            key={step.id}
                            initial={{ opacity: 0, x: -10 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: idx * 0.1 }}
                            className="flex items-center justify-between p-3 bg-gray-50 rounded-xl border border-gray-100"
                          >
                            <div className="flex items-center gap-3">
                              {step.status === 'completed' ? (
                                <div className="bg-green-500 p-1 rounded-full">
                                  <Check className="w-3 h-3 text-white" />
                                </div>
                              ) : step.status === 'loading' ? (
                                <Loader2 className="w-4 h-4 text-green-600 animate-spin" />
                              ) : (
                                <div className="w-4 h-4 rounded-full border-2 border-gray-200" />
                              )}
                              <span className={`text-sm font-medium ${step.status === 'completed' ? 'text-gray-900' : 'text-gray-400'}`}>
                                {step.label}
                              </span>
                            </div>
                            {step.status === 'loading' && (
                              <div className="w-24 h-1.5 bg-gray-200 rounded-full overflow-hidden">
                                <motion.div 
                                  className="h-full bg-green-500"
                                  initial={{ width: 0 }}
                                  animate={{ width: '100%' }}
                                  transition={{ duration: 1, repeat: Infinity }}
                                />
                              </div>
                            )}
                          </motion.div>
                        ))}
                      </div>
                    )}
                  </div>
                </section>

                <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 flex gap-3">
                  <Info className="w-5 h-5 text-blue-500 shrink-0" />
                  <p className="text-xs text-blue-700 leading-relaxed">
                    <strong>{t("tipLabel")}:</strong> {t("tip")}
                  </p>
                </div>
              </div>

              {/* Right Column: Results */}
              <div className="space-y-6">
                <AnimatePresence mode="wait">
                  {result ? (
                    <motion.section 
                      key="result"
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 0.95 }}
                      className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden"
                    >
                      <div className={`h-2 w-full ${result.disease.toLowerCase().includes('healthy') || result.disease.includes('ஆரோக்கியமானது') || result.disease.includes('स्वस्थ') || result.disease.includes('Healthy') ? 'bg-green-500' : 'bg-red-500'}`} />
                      <div className="p-6">
                        <div className="flex items-start justify-between mb-6">
                          <div>
                            <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1">{t("diagnosis")}</p>
                            <h3 className="text-2xl font-bold text-gray-900 leading-tight">{result.disease}</h3>
                          </div>
                          <div className="flex items-center gap-2">
                            <button 
                              onClick={speakResult}
                              disabled={isSpeaking}
                              className={`p-2 rounded-xl border transition-all ${isSpeaking ? 'bg-green-50 border-green-200 text-green-600' : 'bg-gray-50 border-gray-100 text-gray-400 hover:text-green-600'}`}
                            >
                              {isSpeaking ? <Mic className="w-5 h-5 animate-pulse" /> : <MicOff className="w-5 h-5" />}
                            </button>
                            <button 
                              onClick={() => toggleFavorite(result)}
                              className={`p-2 rounded-xl border transition-all ${result.isFavorite ? 'bg-yellow-50 border-yellow-200 text-yellow-500' : 'bg-gray-50 border-gray-100 text-gray-400 hover:text-yellow-500'}`}
                            >
                              <Star className={`w-5 h-5 ${result.isFavorite ? 'fill-yellow-500' : ''}`} />
                            </button>
                            <div className="bg-gray-50 px-3 py-1 rounded-full border border-gray-100">
                              <span className="text-sm font-bold text-green-700">{result.confidence} {t("match")}</span>
                            </div>
                          </div>
                        </div>

                        <div className="mb-6">
                          <div className="flex justify-between text-xs font-bold text-gray-400 uppercase mb-2">
                            <span>{t("confidenceLabel")}</span>
                            <span className="flex items-center gap-2">
                              {result.severity === 'High' ? t("high") : result.severity === 'Medium' ? t("medium") : t("low")} {t("severity")}
                              <div className={`w-2 h-2 rounded-full ${result.severity === 'High' ? 'bg-red-500' : result.severity === 'Medium' ? 'bg-yellow-500' : 'bg-green-500'}`} />
                            </span>
                          </div>
                          <div className="h-2 w-full bg-gray-100 rounded-full overflow-hidden">
                            <motion.div 
                              initial={{ width: 0 }}
                              animate={{ width: result.confidence }}
                              transition={{ duration: 1, ease: "easeOut" }}
                              className={`h-full ${parseInt(result.confidence) > 80 ? 'bg-green-500' : parseInt(result.confidence) > 50 ? 'bg-yellow-500' : 'bg-red-500'}`}
                            />
                          </div>
                        </div>

                        <div className="space-y-6">
                          <div className="bg-green-50 rounded-xl p-4 border border-green-100">
                            <h4 className="text-sm font-bold text-green-800 flex items-center gap-2 mb-2">
                              <CheckCircle2 className="w-4 h-4" />
                              {t("treatment")}
                            </h4>
                            <div className="text-sm text-green-900 leading-relaxed font-medium prose prose-sm prose-green">
                              <Markdown>{result.solution}</Markdown>
                            </div>
                          </div>

                          <div>
                            <h4 className="text-sm font-bold text-gray-900 mb-2">{t("details")}</h4>
                            <div className="text-sm text-gray-600 leading-relaxed prose prose-sm">
                              <Markdown>{result.details}</Markdown>
                            </div>
                          </div>

                          <div className="grid grid-cols-2 gap-3 pt-4">
                            <button 
                              onClick={() => downloadPDF(result, image!)}
                              disabled={isGeneratingPDF}
                              className="flex items-center justify-center gap-2 bg-gray-900 hover:bg-black text-white font-bold py-3 rounded-xl transition-all disabled:opacity-50"
                            >
                              {isGeneratingPDF ? (
                                <RefreshCw className="w-4 h-4 animate-spin" />
                              ) : (
                                <FileText className="w-4 h-4" />
                              )}
                              {t("report")}
                            </button>
                            <button 
                              onClick={reset}
                              className="flex items-center justify-center gap-2 border-2 border-gray-200 hover:border-green-600 hover:text-green-600 text-gray-600 font-bold py-3 rounded-xl transition-all"
                            >
                              <RefreshCw className="w-4 h-4" />
                              {t("newScan")}
                            </button>
                          </div>
                        </div>
                      </div>
                    </motion.section>
                  ) : error ? (
                    <motion.div 
                      key="error"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="bg-red-50 border border-red-100 rounded-2xl p-6 flex flex-col items-center text-center gap-4"
                    >
                      <AlertCircle className="w-12 h-12 text-red-500" />
                      <div>
                        <h3 className="font-bold text-red-900">{t('analysisError')}</h3>
                        <p className="text-sm text-red-700 mt-1">{error}</p>
                      </div>
                      <button 
                        onClick={reset}
                        className="bg-red-600 text-white px-6 py-2 rounded-lg font-bold text-sm hover:bg-red-700 transition-colors"
                      >
                        {t("tryAgain")}
                      </button>
                    </motion.div>
                  ) : (
                    <motion.div 
                      key="empty"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="bg-gray-50 border border-dashed border-gray-200 rounded-2xl p-12 flex flex-col items-center justify-center text-center gap-4 min-h-[400px]"
                    >
                      <div className="bg-white p-4 rounded-full shadow-sm">
                        <Leaf className="w-10 h-10 text-gray-300" />
                      </div>
                      <div>
                        <h3 className="font-bold text-gray-400">{t("noAnalysis")}</h3>
                        <p className="text-sm text-gray-400 mt-1 max-w-[200px]">{t("noAnalysisDesc")}</p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      <footer className="max-w-4xl mx-auto px-4 py-12 border-t border-gray-200 mt-12">
        <div className="flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2 opacity-50">
            <Leaf className="w-4 h-4" />
            <span className="text-xs font-bold uppercase tracking-widest">{t('title')}</span>
          </div>
          <p className="text-xs text-gray-400 text-center md:text-right leading-relaxed max-w-md">
            {t("footerText")}
          </p>
        </div>
      </footer>

      {/* Chatbot Floating Window */}
      <div className="fixed bottom-6 right-6 z-50">
        <AnimatePresence>
          {isChatOpen && (
            <motion.div 
              initial={{ opacity: 0, y: 20, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 20, scale: 0.95 }}
              className="bg-white rounded-2xl shadow-2xl border border-gray-200 w-[350px] sm:w-[400px] h-[500px] flex flex-col overflow-hidden mb-4"
            >
              <div className="bg-green-600 p-4 flex items-center justify-between text-white">
                <div className="flex items-center gap-2">
                  <MessageCircle className="w-5 h-5" />
                  <h3 className="font-bold">{t('askExpert')}</h3>
                </div>
                <button onClick={() => setIsChatOpen(false)}><X className="w-5 h-5" /></button>
              </div>
              
              <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-gray-50">
                {chatMessages.length === 0 && (
                  <div className="text-center py-8">
                    <div className="bg-green-100 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-3">
                      <Leaf className="text-green-600 w-6 h-6" />
                    </div>
                    <p className="text-sm text-gray-500">{t('chatPlaceholder')}</p>
                  </div>
                )}
                {chatMessages.map((msg, i) => (
                  <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                    <div className={`max-w-[80%] p-3 rounded-2xl text-sm ${msg.role === 'user' ? 'bg-green-600 text-white rounded-tr-none' : 'bg-white border border-gray-200 text-gray-800 rounded-tl-none shadow-sm'} prose prose-sm`}>
                      <Markdown>{msg.text}</Markdown>
                    </div>
                  </div>
                ))}
                {isChatLoading && (
                  <div className="flex justify-start">
                    <div className="bg-white border border-gray-200 p-3 rounded-2xl rounded-tl-none shadow-sm">
                      <Loader2 className="w-4 h-4 animate-spin text-green-600" />
                    </div>
                  </div>
                )}
              </div>

              <form onSubmit={sendMessageToChatbot} className="p-4 bg-white border-t border-gray-100 flex gap-2">
                <button 
                  type="button"
                  onClick={startSpeechRecognition}
                  className={`p-2 rounded-xl border transition-all ${isListening ? 'bg-red-50 border-red-200 text-red-600' : 'bg-gray-50 border-gray-100 text-gray-400 hover:text-green-600'}`}
                >
                  <Mic className={`w-5 h-5 ${isListening ? 'animate-pulse' : ''}`} />
                </button>
                <input 
                  type="text" 
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  placeholder={t('chatPlaceholder')}
                  className="flex-1 bg-gray-50 border border-gray-200 rounded-xl px-4 py-2 text-sm outline-none focus:ring-2 focus:ring-green-500 transition-all"
                />
                <button 
                  type="submit"
                  disabled={!chatInput.trim() || isChatLoading}
                  className="bg-green-600 text-white p-2 rounded-xl disabled:opacity-50 transition-all active:scale-95"
                >
                  <Send className="w-5 h-5" />
                </button>
              </form>
            </motion.div>
          )}
        </AnimatePresence>
        
        <button 
          onClick={() => setIsChatOpen(!isChatOpen)}
          className="bg-green-600 text-white p-4 rounded-full shadow-xl hover:bg-green-700 transition-all active:scale-90 flex items-center gap-2 group"
        >
          <MessageCircle className="w-6 h-6" />
          {!isChatOpen && <span className="max-w-0 overflow-hidden group-hover:max-w-xs transition-all duration-300 font-bold whitespace-nowrap">{t('askExpert')}</span>}
        </button>
      </div>

      <audio ref={audioRef} className="hidden" />
    </div>
  );
}
